# Node.js 16 버전의 이미지를 기반으로 설정
FROM node:16

# 작업 디렉토리 설정
WORKDIR /app

# 패키지 파일들을 복사
COPY package*.json ./

# 의존성 설치
RUN npm install

# 소스 파일 복사
COPY . .

# 애플리케이션 실행
CMD ["npm", "start"]

# 포트 설정 (예: 3000번 포트)
EXPOSE 3000
